#!/usr/bin/env python3
"""
Spellcaster Installer Asset Generator
======================================
Renders the installer's branded artwork by submitting workflows to a
ComfyUI server that already has Spellcaster installed. The whole pitch
of this script: the installer's polish is generated by the very engine
the installer installs.

Catalog (49 assets, ~22-25 min on a mid-tier GPU):
  -  7 feature category badges     (256×256)   Magic Profiles step
  -  8 architecture sigils         (192×192)   Per-arch identity
  -  8 wizard-step backgrounds    (1280×720)   Ambient art per step
  -  6 use-case hero cards         (800×600)   What You Want step
  -  1 sidebar wizard companion    (384×640)   Recurring sidebar figure
  -  1 welcome hero (cinematic)   (1920×600)   Top-of-welcome banner
  -  1 completion celebration     (1024×1024)  Triumphant finale
  -  1 error state sigil           (256×256)   Calm "something went wrong"
  - 16 loading frames (8 pulse + 8 spin) (256×256)
        Frame 1 = txt2img base; frames 2-8 = img2img chain with
        ~0.45 denoise + slight prompt morph for organic motion.

Outputs go to ``assets/installer/`` so the installer can find them via
``theme.asset(name)`` (theme.py:_candidate_roots already searches the
parent assets/ dir). Committed to the SFW repo and bundled into every
PyInstaller build.

Usage:
    python tools/generate_installer_assets.py
    python tools/generate_installer_assets.py --server http://192.168.x.x:8188
    python tools/generate_installer_assets.py --only feature
    python tools/generate_installer_assets.py --only feature,arch,loading
    python tools/generate_installer_assets.py --list
    python tools/generate_installer_assets.py --dry-run

Re-runnable: existing files are skipped unless --overwrite is passed.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request
import uuid
from pathlib import Path

REPO_ROOT  = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "assets" / "installer"
DEFAULT_SERVER = "http://127.0.0.1:8188"

# ── Negative prompts (kept minimal — these are illustrations, not photos)
NEG_BADGE = "photograph, real person, text, watermark, signature, letters, logo, low quality, blurry, jpeg artifacts, frame border, multiple objects, busy"
NEG_HERO  = "text, watermark, signature, letters, logo, low quality, blurry, jpeg artifacts, deformed, ugly, ungainly composition"

# ── Style modifiers (bolted onto every prompt to keep family identity)
STYLE_BADGE = ("centered emblem, ornate art nouveau filigree, illuminated manuscript style, "
               "rich purple and gold palette, soft inner glow, subtle bloom, "
               "transparent black background, isolated subject, vector-friendly clean edges, masterpiece")
STYLE_SIGIL = ("magical sigil, alchemical glyph, glowing runes, "
               "geometric symmetry, intricate metalwork, gem inlay, "
               "deep void background, hairline gold accents, mystical, masterpiece")
STYLE_AMBIENT = ("subtle background art, atmospheric, dim violet lighting, "
                 "ethereal mist, depth of field, painterly, low-contrast, "
                 "cinematic widescreen composition, no people, no text, masterpiece")
STYLE_HERO   = ("epic wide composition, cinematic lighting, dramatic atmosphere, "
                "deep purple and gold palette, soft volumetric god rays, painterly, "
                "highly detailed, hyper-detailed environment, masterpiece, 8k")

# ─────────────────────────────────────────────────────────────────────
# Asset catalog — data-driven, edit here to evolve the brand
# ─────────────────────────────────────────────────────────────────────

ASSETS: list[dict] = []

# Default render knobs — overridden per-asset for the showpieces
DEFAULT_STEPS = 32
DEFAULT_CFG = 6.5
DEFAULT_SAMPLER = "dpmpp_2m_sde"
DEFAULT_SCHEDULER = "karras"

# ── 7 feature category badges (Magic Profiles step) ────────────────
_FEATURE_BADGES = [
    ("generation",   "single radiant orb of pure light suspended over open hands, magic sparks, conjuring gesture"),
    ("restoration",  "golden phoenix rising from ashes, wings spread wide, tail of glowing embers"),
    ("styling",      "ornate paintbrush dripping liquid gold and rainbow ink, swirling brush trails"),
    ("identity",     "silver venetian mask floating in mid-air, surrounded by drifting light particles"),
    ("video",        "vintage film reel transforming into a strip of glowing magical photographs, motion trail"),
    ("metadata",     "open scroll with glowing runes, quill writing in gold ink, wax seal"),
    ("controlnet",   "golden ornate compass with pentagonal needle, glyph circles around it, surveying lines"),
]
for key, subject in _FEATURE_BADGES:
    ASSETS.append({
        "category": "feature",
        "key": f"feature_{key}",
        "filename": f"feature_{key}.png",
        "size": (1024, 1024),  # render large, downscale on use
        "final_size": (256, 256),
        "model_class": "sdxl_clean",
        "prompt": f"{subject}, {STYLE_BADGE}",
        "negative": NEG_BADGE,
        "steps": 35,  # bump for crisp emblem detail
    })

# ── 8 architecture sigils (per-arch identity) ──────────────────────
# Color hint per arch follows the GIMP plugin theme variants
_ARCH_SIGILS = [
    ("klein",       "five-pointed pentacle of beaten gold, central garnet, beams of warm yellow light",                         "gold"),
    ("flux",        "cyan lightning bolt encased in a hexagonal crystal, electric arcs",                                          "cyan"),
    ("sdxl",        "intricate brass clockwork gear with tiny gemstones, amber glow, steampunk emblem",                          "amber"),
    ("wan",         "stylized blue wave breaking inside a circular frame, foam particles, oceanic energy",                      "blue"),
    ("chroma",      "triangular prism splitting white light into a fan of rainbow colors, geometric facets",                    "rainbow"),
    ("illustrious", "violet six-pointed star with smaller stars orbiting, nebula background contained inside the frame",        "violet"),
    ("zit",         "minimalist black diamond shape with thin red accents, sharp angular geometry",                              "red"),
    ("ltx",         "azure river flowing in a perfect circle, suggested motion blur, ribbon of water",                          "azure"),
]
for key, subject, color in _ARCH_SIGILS:
    ASSETS.append({
        "category": "arch",
        "key": f"arch_{key}",
        "filename": f"arch_{key}.png",
        "size": (1024, 1024),
        "final_size": (192, 192),
        "model_class": "sdxl_clean",
        "prompt": f"{subject}, {color} dominant color, {STYLE_SIGIL}",
        "negative": NEG_BADGE,
        "steps": 35,
    })

# ── 8 step backgrounds (subtle ambient art, blurred wallpaper-quality) ─
_STEP_BACKGROUNDS = [
    ("welcome",   "vast wizard's library, towering bookshelves disappearing into purple mist, single beam of light from above"),
    ("detect",    "alchemy laboratory at dusk, glassware catching candlelight, soft shadows on stone walls"),
    ("setup",     "open spellbook on a workbench, quill, scattered crystals, warm desk lamp"),
    ("system",    "ancient observatory tower interior, brass orrery turning slowly, starlight through arched windows"),
    ("models",    "vault of glowing artifacts in glass cases, deep blue ambient lighting, museum-like mystical archive"),
    ("profiles",  "round table with seven glowing emblems carved into the wood, soft top-down lighting"),
    ("components",  "long apothecary shelves filled with potion bottles, soft amber light, depth of field"),
    ("deploy",    "stone circle at twilight, ley lines glowing on the ground, distant mountains, a sense of arrival"),
]
for key, subject in _STEP_BACKGROUNDS:
    ASSETS.append({
        "category": "background",
        "key": f"bg_{key}",
        "filename": f"bg_{key}.png",
        "size": (1280, 720),
        "final_size": (1280, 720),
        "model_class": "sdxl_realistic",
        "prompt": f"{subject}, {STYLE_AMBIENT}",
        "negative": NEG_HERO,
        "steps": 42,  # painterly atmospheres benefit from extra refinement
        "sampler": "euler_ancestral",
        "scheduler": "normal",
    })

# ── 6 use-case hero cards (What You Want step) ─────────────────────
# Vignettes that visually narrate what each use-case DOES. Drawn into
# 800×600 cards on Step 2 to replace the current text-only treatment.
_USECASE_CARDS = [
    ("text_to_image", "wizard at a stone podium conjuring a glowing portrait from blank parchment, light streaming upward from the page"),
    ("img2img",       "magical pencil tracing over an existing oil portrait, the portrait subtly transforming under the pencil's gold-light tip"),
    ("inpaint",       "cracked Renaissance painting being repaired by glowing thread weaving across the damaged area, gold restoration"),
    ("face_swap",     "two ornate venetian masks face-to-face, threads of golden light crossing between them, identity exchange"),
    ("video",         "magical lantern projecting a film strip into the air, frames lifting and animating outward, motion blur trails"),
    ("restoration",   "weathered antique photograph being healed by golden filaments, sepia turning vibrant, time reversed"),
]
for key, subject in _USECASE_CARDS:
    ASSETS.append({
        "category": "usecase",
        "key": f"usecase_{key}",
        "filename": f"usecase_{key}.png",
        "size": (1024, 768),
        "final_size": (800, 600),
        "model_class": "sdxl_realistic",
        "prompt": f"{subject}, {STYLE_HERO}",
        "negative": NEG_HERO,
        "steps": 38,
    })

# ── 1 sidebar wizard companion (recurring vertical figure) ─────────
ASSETS.append({
    "category": "companion",
    "key": "sidebar_companion",
    "filename": "sidebar_companion.png",
    "size": (768, 1280),  # vertical portrait, fits the sidebar
    "final_size": (384, 640),
    "model_class": "sdxl_realistic",
    "prompt": ("tall slender wise wizard holding a glowing staff vertically, "
               "deep purple cloak with gold embroidery, hood casting a soft shadow, "
               "calm watchful presence, three-quarter facing camera, "
               f"deep purple background fading to black, full body, {STYLE_HERO}"),
    "negative": NEG_HERO + ", multiple people, crowd, group",
    "steps": 42,
})

# ── 1 welcome hero (cinematic banner across the top) ───────────────
ASSETS.append({
    "category": "hero",
    "key": "hero_welcome",
    "filename": "hero_welcome.png",
    "size": (1920, 832),  # SDXL handles 1920×832; cropped to 1920×600 on use
    "final_size": (1920, 600),
    "model_class": "sdxl_realistic",
    "prompt": ("breathtaking wizard's atelier overlooking a starlit valley, archways framing distant mountains, "
               "floating arcane instruments, magic constellations swirling in the sky, "
               f"warm golden hour, {STYLE_HERO}"),
    "negative": NEG_HERO,
    "steps": 50,  # showpiece — render at full quality
})

# ── 1 completion celebration (fullscreen takeover) ────────────────
ASSETS.append({
    "category": "completion",
    "key": "completion_celebration",
    "filename": "completion_celebration.png",
    "size": (1024, 1024),
    "final_size": (1024, 1024),
    "model_class": "sdxl_realistic",
    "prompt": ("triumphant wizard silhouette with arms raised, beams of golden light bursting outward, "
               "magical sparks raining down, sense of arrival and completion, "
               f"painted celebration scene, victorious, {STYLE_HERO}"),
    "negative": NEG_HERO,
    "steps": 50,  # other showpiece
})

# ── 1 error sigil (calm reassuring 'something went wrong') ────────
ASSETS.append({
    "category": "error",
    "key": "error_sigil",
    "filename": "error_sigil.png",
    "size": (1024, 1024),
    "final_size": (256, 256),
    "model_class": "sdxl_clean",
    "prompt": ("snuffed candle with a single curl of smoke rising, melted golden wax pooling, "
               f"calm composition, not threatening, {STYLE_BADGE}"),
    "negative": NEG_BADGE,
    "steps": 35,
})

# ── 16 loading frames (two 8-frame sequences via img2img chain) ───
# Each sequence: frame 1 = txt2img base; frames 2-8 = img2img with low
# denoise (preserves the base composition) + a subtle prompt morph that
# nudges the visual phase. Result: organic frame-to-frame motion that
# looks like the magic itself is alive, not a 1-frame PIL rotation.
_LOADING_SEQUENCES = [
    {
        "key": "loading_pulse",
        "frames": 8,
        "base_prompt": "single golden orb pulsing inside concentric runic rings, suspended in violet space",
        "frame_morphs": [
            "calm dim glow",            # 1 — softest
            "soft glow growing",         # 2
            "warmer glow brightening",   # 3
            "bright pulsing aura",       # 4 — peak
            "blinding peak radiance",    # 5 — apex
            "aura softening",            # 6
            "warm glow fading",          # 7
            "dim glow returning",        # 8 — loops back to 1
        ],
    },
    {
        "key": "loading_spin",
        "frames": 8,
        "base_prompt": "ornate golden pentacle made of liquid metal, suspended in deep purple void, with subtle motion blur",
        "frame_morphs": [
            "tilted 0 degrees",
            "tilted 45 degrees",
            "tilted 90 degrees",
            "tilted 135 degrees",
            "tilted 180 degrees",
            "tilted 225 degrees",
            "tilted 270 degrees",
            "tilted 315 degrees",
        ],
    },
]
for seq in _LOADING_SEQUENCES:
    for i in range(seq["frames"]):
        morph = seq["frame_morphs"][i]
        ASSETS.append({
            "category": "loading",
            "key": f"{seq['key']}_{i:02d}",
            "filename": f"{seq['key']}_{i:02d}.png",
            "size": (1024, 1024),
            "final_size": (256, 256),
            "model_class": "sdxl_clean",
            # Frame 0 is pure txt2img; frames 1-7 add img2img chain meta
            "prompt": f"{seq['base_prompt']}, {morph}, {STYLE_SIGIL}",
            "negative": NEG_BADGE,
            "steps": 28,
            # Sequence chaining metadata (read by the runner)
            "chain_seq": seq["key"],   # which sequence we belong to
            "chain_idx": i,             # 0 = base txt2img, 1..N = img2img refs
            "chain_denoise": 0.45,      # img2img denoise for non-base frames
        })


# ─────────────────────────────────────────────────────────────────────
# Workflow helpers
# ─────────────────────────────────────────────────────────────────────

def _txt2img_workflow(ckpt: str, prompt: str, negative: str,
                      width: int, height: int, *,
                      steps: int = 28, cfg: float = 6.5,
                      sampler: str = "dpmpp_2m_sde",
                      scheduler: str = "karras",
                      seed: int | None = None) -> dict:
    """SDXL txt2img workflow — mirrors generate_showcase.txt2img()."""
    s = seed if seed is not None else int.from_bytes(os.urandom(4), "big")
    return {
        "1": {"class_type": "CheckpointLoaderSimple",
              "inputs": {"ckpt_name": ckpt}},
        "2": {"class_type": "CLIPTextEncode",
              "inputs": {"text": prompt, "clip": ["1", 1]}},
        "3": {"class_type": "CLIPTextEncode",
              "inputs": {"text": negative, "clip": ["1", 1]}},
        "4": {"class_type": "EmptyLatentImage",
              "inputs": {"width": width, "height": height, "batch_size": 1}},
        "5": {"class_type": "KSampler",
              "inputs": {"model": ["1", 0], "positive": ["2", 0],
                         "negative": ["3", 0], "latent_image": ["4", 0],
                         "seed": s, "steps": steps, "cfg": cfg,
                         "sampler_name": sampler, "scheduler": scheduler,
                         "denoise": 1.0}},
        "6": {"class_type": "VAEDecode",
              "inputs": {"samples": ["5", 0], "vae": ["1", 2]}},
        "7": {"class_type": "SaveImage",
              "inputs": {"images": ["6", 0],
                         "filename_prefix": "installer_asset"}},
    }


def _img2img_workflow(ckpt: str, prompt: str, negative: str,
                      input_image_name: str, *,
                      denoise: float = 0.45,
                      steps: int = 28, cfg: float = 6.5,
                      sampler: str = "dpmpp_2m_sde",
                      scheduler: str = "karras",
                      seed: int | None = None) -> dict:
    """img2img workflow seeded from an uploaded image — used for the
    loading-sequence frame chain. Lower denoise preserves the base
    composition while the prompt morph nudges the visual phase."""
    s = seed if seed is not None else int.from_bytes(os.urandom(4), "big")
    return {
        "1": {"class_type": "CheckpointLoaderSimple",
              "inputs": {"ckpt_name": ckpt}},
        "2": {"class_type": "CLIPTextEncode",
              "inputs": {"text": prompt, "clip": ["1", 1]}},
        "3": {"class_type": "CLIPTextEncode",
              "inputs": {"text": negative, "clip": ["1", 1]}},
        "4": {"class_type": "LoadImage",
              "inputs": {"image": input_image_name}},
        "5": {"class_type": "VAEEncode",
              "inputs": {"pixels": ["4", 0], "vae": ["1", 2]}},
        "6": {"class_type": "KSampler",
              "inputs": {"model": ["1", 0], "positive": ["2", 0],
                         "negative": ["3", 0], "latent_image": ["5", 0],
                         "seed": s, "steps": steps, "cfg": cfg,
                         "sampler_name": sampler, "scheduler": scheduler,
                         "denoise": denoise}},
        "7": {"class_type": "VAEDecode",
              "inputs": {"samples": ["6", 0], "vae": ["1", 2]}},
        "8": {"class_type": "SaveImage",
              "inputs": {"images": ["7", 0],
                         "filename_prefix": "installer_asset_chain"}},
    }


def upload_image(server: str, local_path: Path,
                 upload_name: str | None = None) -> str:
    """Upload a PNG to ComfyUI's input dir; returns the server-side filename."""
    import mimetypes
    if upload_name is None:
        upload_name = f"installer_chain_{uuid.uuid4().hex[:8]}.png"
    boundary = uuid.uuid4().hex
    ctype = mimetypes.guess_type(str(local_path))[0] or "image/png"
    with open(local_path, "rb") as f:
        data = f.read()
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="image"; '
        f'filename="{upload_name}"\r\n'
        f"Content-Type: {ctype}\r\n\r\n"
    ).encode() + data + f"\r\n--{boundary}--\r\n".encode()
    req = urllib.request.Request(
        f"{server}/upload/image", data=body,
        headers={"Content-Type":
                 f"multipart/form-data; boundary={boundary}"},
        method="POST")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read()).get("name", upload_name)


# ─────────────────────────────────────────────────────────────────────
# Model selection — auto-detect from server's checkpoint inventory
# ─────────────────────────────────────────────────────────────────────

# Substring matching is order-sensitive: we walk hints in priority and return
# the first match whose path also passes class_filter(). Filters keep us from
# accidentally choosing an SD 1.5 ckpt when we asked for SDXL.
_MODEL_CLASS_HINTS: dict[str, list[str]] = {
    "sdxl_realistic": [
        "juggernautxl", "realvisxl", "rundiffusion", "epicrealism",
        "sdxl_real", "realistic",
    ],
    "sdxl_clean": [
        "moderndisney", "modern_disney", "modernpixar",
        "noobai", "ilustreal", "pixar", "disney", "anime", "stylized",
    ],
}

# Path-segment exclusion patterns per class. We disqualify candidates whose
# normalized path contains any of these tokens — eg. /SD-1.5/, /sd15/.
_CLASS_EXCLUDE: dict[str, list[str]] = {
    "sdxl_realistic": ["sd-1.5/", "sd15/", "sd1.5/", "/flux/", "/wan/", "/ltx/", "/chroma/"],
    "sdxl_clean":     ["sd-1.5/", "sd15/", "sd1.5/", "/flux/", "/wan/", "/ltx/", "/chroma/"],
}

# Class-specific positive REQUIRE: every candidate path MUST contain at least
# one of these substrings to be considered. Belt-and-suspenders against
# matching the wrong arch.
_CLASS_REQUIRE: dict[str, list[str]] = {
    "sdxl_realistic": ["sdxl/", "sdxl\\", "_xl_", "xl_v", "xl-v"],
    "sdxl_clean":     ["sdxl/", "sdxl\\", "_xl_", "xl_v", "xl-v"],
}


def fetch_checkpoints(server: str) -> list[str]:
    """Probe /object_info/CheckpointLoaderSimple for installed ckpt names."""
    try:
        with urllib.request.urlopen(
                f"{server}/object_info/CheckpointLoaderSimple", timeout=15) as r:
            data = json.loads(r.read())
        items = (data.get("CheckpointLoaderSimple", {}).get("input", {})
                 .get("required", {}).get("ckpt_name", [None])[0])
        return list(items) if isinstance(items, list) else []
    except Exception as exc:  # noqa: BLE001
        print(f"  ERROR: could not fetch checkpoints: {exc}")
        return []


def _passes_class_filter(class_key: str, ckpt: str) -> bool:
    """Apply per-class require/exclude rules — guards against arch mismatch."""
    norm = ckpt.replace("\\", "/").lower()
    for token in _CLASS_EXCLUDE.get(class_key, []):
        if token in norm:
            return False
    require = _CLASS_REQUIRE.get(class_key, [])
    if require and not any(tok in norm for tok in require):
        return False
    return True


def pick_model(class_key: str, available: list[str]) -> str | None:
    """Choose the first checkpoint matching the class's hint + filter rules.

    Falls back to the first checkpoint that PASSES the class filter even if
    no positive hint matched (covers users with non-canonically-named SDXL
    models). Returns None if nothing in inventory satisfies the class.
    """
    eligible = [(c, c.lower()) for c in available
                if _passes_class_filter(class_key, c)]
    hints = _MODEL_CLASS_HINTS.get(class_key, [])
    for hint in hints:
        for orig, low in eligible:
            if hint in low:
                return orig
    # No positive hint matched, but at least one model passes the class
    # filter — use it. Better than crashing or picking the wrong arch.
    return eligible[0][0] if eligible else None


# ─────────────────────────────────────────────────────────────────────
# Queue + wait + save
# ─────────────────────────────────────────────────────────────────────

def queue_prompt(server: str, workflow: dict) -> str | None:
    payload = json.dumps({"prompt": workflow,
                          "client_id": str(uuid.uuid4())}).encode()
    req = urllib.request.Request(
        f"{server}/prompt", data=payload,
        headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read()).get("prompt_id")
    except urllib.error.HTTPError as e:
        body = e.read().decode(errors="replace")
        print(f"    ERROR {e.code}: {body[:300]}")
        return None
    except Exception as e:  # noqa: BLE001
        print(f"    ERROR: {e}")
        return None


def wait_and_fetch(server: str, prompt_id: str,
                   timeout: int = 600) -> bytes | None:
    start = time.time()
    while time.time() - start < timeout:
        try:
            with urllib.request.urlopen(
                    f"{server}/history/{prompt_id}", timeout=10) as r:
                hist = json.loads(r.read())
            if prompt_id not in hist:
                time.sleep(2); continue
            outs = hist[prompt_id].get("outputs", {})
            for node_out in outs.values():
                images = node_out.get("images") or []
                if images:
                    img = images[0]
                    fn = img["filename"]
                    sub = img.get("subfolder", "")
                    typ = img.get("type", "output")
                    url = (f"{server}/view?filename={fn}"
                           f"&subfolder={sub}&type={typ}")
                    with urllib.request.urlopen(url, timeout=60) as r:
                        return r.read()
            time.sleep(2)
        except Exception:
            time.sleep(2)
    return None


def downscale_save(blob: bytes, dest: Path,
                   final_size: tuple[int, int]) -> None:
    """Decode, resize with Lanczos, save PNG."""
    try:
        from PIL import Image
        import io
        img = Image.open(io.BytesIO(blob))
        if img.size != final_size:
            img = img.resize(final_size, Image.LANCZOS)
        dest.parent.mkdir(parents=True, exist_ok=True)
        img.save(dest, "PNG", optimize=True)
    except ImportError:
        # No Pillow — write the raw blob and let downstream resize
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(blob)


# ─────────────────────────────────────────────────────────────────────
# Driver
# ─────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--server", default=DEFAULT_SERVER,
                        help=f"ComfyUI server URL (default: {DEFAULT_SERVER})")
    parser.add_argument("--only", default="",
                        help="Comma-separated category filter "
                             "(feature,arch,background,hero,completion,error,loading)")
    parser.add_argument("--list", action="store_true",
                        help="Print the asset catalog and exit")
    parser.add_argument("--dry-run", action="store_true",
                        help="Resolve models + prompts, but skip generation")
    parser.add_argument("--overwrite", action="store_true",
                        help="Re-render even if output already exists")
    parser.add_argument("--seed", type=int, default=None,
                        help="Fixed seed for reproducible runs")
    args = parser.parse_args()

    if args.list:
        for a in ASSETS:
            print(f"  {a['category']:11s} {a['key']:28s} "
                  f"{a['size'][0]}×{a['size'][1]:<5d} -> {a['filename']}")
        print(f"\n  Total: {len(ASSETS)} assets")
        return 0

    server = args.server.rstrip("/")
    only = {c.strip() for c in args.only.split(",") if c.strip()}
    jobs = [a for a in ASSETS if not only or a["category"] in only]

    print(f"\n{'='*64}")
    print(f"  Spellcaster Installer Asset Generator")
    print(f"  Server:  {server}")
    print(f"  Assets:  {len(jobs)}{f' ({args.only})' if only else ''}")
    print(f"  Output:  {OUTPUT_DIR.relative_to(REPO_ROOT)}")
    print(f"{'='*64}\n")

    # Probe server for available models
    print("Probing checkpoint inventory…")
    available = fetch_checkpoints(server)
    if not available:
        print("  No checkpoints reachable. Aborting.")
        return 2
    print(f"  {len(available)} checkpoints available")

    # Resolve a concrete ckpt for each model_class actually used
    used_classes = sorted({j["model_class"] for j in jobs})
    resolved: dict[str, str] = {}
    for cls in used_classes:
        m = pick_model(cls, available)
        if not m:
            print(f"  WARN: no checkpoint matched class '{cls}'")
            continue
        resolved[cls] = m
        print(f"  {cls:18s} -> {m}")

    if args.dry_run:
        print("\n[dry-run] not generating. Re-run without --dry-run to render.")
        return 0

    print(f"\nRendering {len(jobs)} assets…\n")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Group chain-sequence specs so a sequence's frames render in order
    # using the same RNG seed (so the chain's morph is coherent).
    seq_seeds: dict[str, int] = {}

    ok = 0
    skip = 0
    fail = 0
    t0 = time.time()
    for i, spec in enumerate(jobs, 1):
        dest = OUTPUT_DIR / spec["filename"]
        if dest.exists() and not args.overwrite:
            print(f"  [{i:2d}/{len(jobs)}] SKIP (exists) {spec['filename']}")
            skip += 1
            continue
        ckpt = resolved.get(spec["model_class"])
        if not ckpt:
            print(f"  [{i:2d}/{len(jobs)}] FAIL no model for "
                  f"{spec['model_class']}: {spec['filename']}")
            fail += 1
            continue

        w, h = spec["size"]
        steps = spec.get("steps", DEFAULT_STEPS)
        cfg = spec.get("cfg", DEFAULT_CFG)
        sampler = spec.get("sampler", DEFAULT_SAMPLER)
        scheduler = spec.get("scheduler", DEFAULT_SCHEDULER)

        # Sequence handling: chain_idx 0 = txt2img base, 1.. = img2img refs
        chain_seq = spec.get("chain_seq")
        chain_idx = spec.get("chain_idx", 0)

        # Reuse one seed per sequence so all frames build on the same look
        if chain_seq:
            if chain_seq not in seq_seeds:
                seq_seeds[chain_seq] = (args.seed if args.seed is not None
                                        else int.from_bytes(os.urandom(4),
                                                            "big"))
            seed = seq_seeds[chain_seq]
        else:
            seed = args.seed

        if chain_seq and chain_idx > 0:
            # img2img frame — needs the previous frame uploaded
            prev_filename = spec["filename"].rsplit("_", 1)[0] \
                            + f"_{chain_idx - 1:02d}.png"
            prev_path = OUTPUT_DIR / prev_filename
            if not prev_path.exists():
                print(f"  [{i:2d}/{len(jobs)}] FAIL chain prev missing: "
                      f"{prev_filename}")
                fail += 1
                continue
            try:
                uploaded = upload_image(server, prev_path)
            except Exception as e:  # noqa: BLE001
                print(f"  [{i:2d}/{len(jobs)}] FAIL upload: {e}")
                fail += 1
                continue
            wf = _img2img_workflow(
                ckpt, spec["prompt"], spec["negative"],
                input_image_name=uploaded,
                denoise=spec.get("chain_denoise", 0.45),
                steps=steps, cfg=cfg, sampler=sampler, scheduler=scheduler,
                seed=seed)
            label = f"img2img f{chain_idx} ({w}×{h})"
        else:
            wf = _txt2img_workflow(
                ckpt, spec["prompt"], spec["negative"], w, h,
                steps=steps, cfg=cfg, sampler=sampler, scheduler=scheduler,
                seed=seed)
            label = f"({w}×{h}, {steps}st)"

        print(f"  [{i:2d}/{len(jobs)}] {spec['filename']} {label} … ",
              end="", flush=True)
        pid = queue_prompt(server, wf)
        if not pid:
            print("FAIL queue")
            fail += 1
            continue
        blob = wait_and_fetch(server, pid)
        if not blob:
            print("FAIL no output")
            fail += 1
            continue
        downscale_save(blob, dest, spec["final_size"])
        size_kb = dest.stat().st_size / 1024
        print(f"OK ({size_kb:.0f} KB)")
        ok += 1

    elapsed = time.time() - t0
    print(f"\n{'='*64}")
    print(f"  Done in {elapsed:.0f}s — {ok} OK, {skip} skipped, {fail} failed")
    print(f"  Output dir: {OUTPUT_DIR}")
    print(f"{'='*64}\n")
    return 0 if fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
