"""Build a standalone Spellcaster Antenna binary via PyInstaller.

Outputs
-------
    dist/spellcaster-antenna-windows.exe  (on Windows)
    dist/spellcaster-antenna-linux        (on Linux)
    dist/spellcaster-antenna-macos        (on macOS)

The binary is a one-file bundle — double-click to launch the tray
(Windows) or the console mode (Linux/macOS without AppIndicator). It
embeds every antenna dependency (pystray, Pillow, stdlib) plus the
scaffold / spellcaster_core modules the antenna imports lazily.

First launch still runs the install_shortcuts prompt on Windows,
writes its token + config to %USERPROFILE%\.spellcaster\, and shows
the 6-digit pair code in the tray.
"""
from __future__ import annotations

import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent


def _out_name() -> str:
    tag = {"Windows": "windows", "Linux": "linux",
            "Darwin": "macos"}.get(platform.system(), "unknown")
    ext = ".exe" if platform.system() == "Windows" else ""
    return f"spellcaster-antenna-{tag}{ext}"


def main() -> int:
    out_name = _out_name()
    print(f"[antenna-build] Target: {out_name}")
    print(f"[antenna-build] Repo:   {REPO_ROOT}")

    # Clean prior build artefacts so PyInstaller doesn't trip on stale state.
    build_dir = REPO_ROOT / "installer" / "antenna_build"
    spec_dir = REPO_ROOT / "installer" / "antenna_spec"
    dist_dir = REPO_ROOT / "dist"
    for d in (build_dir, spec_dir):
        if d.exists():
            shutil.rmtree(d, ignore_errors=True)
    dist_dir.mkdir(parents=True, exist_ok=True)

    # Entry point: a tiny shim that imports antenna and runs main().
    entry = REPO_ROOT / "installer" / "antenna_entry.py"
    entry.write_text(
        "# auto-generated by build_antenna_exe.py\n"
        "import sys\n"
        "from antenna.__main__ import main\n"
        "sys.exit(main() or 0)\n",
        encoding="utf-8",
    )

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile",
        "--name", out_name.rsplit(".", 1)[0] if "." in out_name else out_name,
        "--workpath", str(build_dir),
        "--specpath", str(spec_dir),
        "--distpath", str(dist_dir),
        "--clean",
        "--noconfirm",
        # Paths PyInstaller searches when resolving imports. Adding the
        # repo root + comfyui-spellcaster/ makes antenna/, scaffold/,
        # and spellcaster_core/ all directly importable without data
        # copies — the freezer collects the whole package graph.
        "--paths", str(REPO_ROOT),
        "--paths", str(REPO_ROOT / "comfyui-spellcaster"),
        # Antenna submodules are lazily imported inside _build_routes /
        # autopopulate_services / tray worker threads; PyInstaller's
        # static analyser misses them, so list them explicitly.
        "--collect-submodules", "antenna",
        "--collect-submodules", "scaffold",
        "--collect-submodules", "spellcaster_core",
        # Tkinter — PyInstaller does NOT auto-bundle Tcl/Tk; the
        # first-run shortcut dialog needs it. --collect-all ensures
        # the _tkinter C extension + the tcl/tk runtime DLLs land in
        # the onefile bundle.
        "--collect-all", "tkinter",
        # Native tray backends per OS — plus PIL's tk finder which pystray's
        # notification path imports on demand.
        "--hidden-import", "pystray._win32",
        "--hidden-import", "pystray._darwin",
        "--hidden-import", "pystray._appindicator",
        "--hidden-import", "PIL._tkinter_finder",
        # remote_services.json is read by installer/remote_services.py
        # at boot; it's a pure data file so --add-data is still the
        # right tool here.
        "--add-data", (f"{REPO_ROOT / 'installer' / 'remote_services.json'}"
                        f"{os.pathsep}installer"),
    ]
    # Windows: tray-only (--noconsole). Use build_antenna_exe_debug.py
    # if you need a console build for troubleshooting; the shipped
    # binary should always be windowless so the user sees the tray
    # icon and nothing else. Tracebacks land in the log file the
    # antenna writes into %USERPROFILE%\.spellcaster\antenna.log via
    # antenna.agent — they're not silently dropped.
    if platform.system() == "Windows":
        cmd.append("--noconsole")
    cmd.append(str(entry))

    print(f"[antenna-build] PyInstaller cmd:\n  {' '.join(cmd)}")
    r = subprocess.run(cmd, cwd=str(REPO_ROOT))
    if r.returncode != 0:
        print(f"[antenna-build] PyInstaller failed with exit {r.returncode}")
        return r.returncode

    produced = dist_dir / out_name
    if not produced.is_file():
        # PyInstaller strips the extension on non-Windows
        alt = dist_dir / out_name.rsplit(".", 1)[0]
        if alt.is_file():
            produced = alt
    if produced.is_file():
        size_mb = produced.stat().st_size / (1024 * 1024)
        print(f"[antenna-build] OK: {produced} ({size_mb:.1f} MB)")
        return 0
    print(f"[antenna-build] FAIL: {produced} not found")
    return 2


if __name__ == "__main__":
    sys.exit(main())
